/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/Button/src/Button.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    I18nDropdown: typeof import('./src/components/I18nDropdown/src/I18nDropdown.vue')['default']
    Navigator: typeof import('./src/components/Navigator/src/Navigator.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
